# Generated by Django 4.2.3 on 2023-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
